name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download SDL2
      uses: albin-johansson/download-sdl2@latest
      with:
        # The version of SDL2 that will be downloaded
        version: 2.28.2
        # Where the SDL2 sources will be saved
        sources_destination: .
        # Where the SDL2 runtime binaries will be saved
        binaries_destination: .
  
    - name: Download SDL2_image
      uses: albin-johansson/download-sdl2-image@latest
      with:
        # The version of SDL2_image that will be downloaded
        version: 2.6.3
        # Where the SDL2_image sources will be saved
        sources_destination: .
        # Where the SDL2_image runtime binaries will be saved
        binaries_destination: .

    - name: download enet
      # run: |
      #   wget http://enet.bespin.org/download/enet-1.3.17.tar.gz
      #   tar -xzf enet-1.3.17.tar.gz

      shell: powershell
      run: |
        Invoke-WebRequest -Uri "http://enet.bespin.org/download/enet-1.3.17.tar.gz" `
                          -OutFile enet-1.3.17.tar.gz
        7z x -y enet-1.3.17.tar.gz


    - name: Setup MSVC Developer Command Prompt
      # You may pin to the exact commit or the version.
      # uses: TheMrMilchmann/setup-msvc-dev@b505cd82c5ee620766f109e9fc377c723376c877
      uses: TheMrMilchmann/setup-msvc-dev@v2.0.1
      with:
        # The target architecture
        arch: x86
        # The path to the Visual Studio installation
        vs-path: .
        # Windows SDK to use
        sdk: 8.1
        # Use Visual Studio libraries with Spectre mitigations
        spectre: true
        # VC++ compiler toolset version
        toolset: 14.0
        # Build for Universal Windows Platform
        uwp: true
        # The environment variable to store the path to vcvarsall.bat in
        export-path-to-vcvarsall: .
        # The environment variable to store the path to the Visual Studio installation in
        export-path-to-vs: .

    
    - name: compile
      run: |
        cl /ISDL2_Sources\include src/server.c src/client.c src/gui.c src/main.c src/highscoreInfo.c /link /LIBPATH:SDL2-2.0.16\lib\x86 /SUBSYSTEM:WINDOWS shell32.lib SDL2.lib SDL2main.lib

    - name: Upload Windows version
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: lunatic_fairy # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          main.exe
          img
